const state={user:null,role:null,questions:[],resources:[],tasks:[],submissions:[],views:[],stuQuestions:[]}
const els={loginSection:document.getElementById('login-section'),topNav:document.getElementById('top-nav'),studentSection:document.getElementById('student-section'),teacherSection:document.getElementById('teacher-section')}
const ui={tabs:(root)=>{root.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{root.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');root.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.getElementById(b.getAttribute('data-tab')).classList.add('active')}))}}
const store={get:(k,def)=>{try{return JSON.parse(localStorage.getItem(k))??def}catch(e){return def}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))}
const enc={e:(s)=>btoa(unescape(encodeURIComponent(s))),d:(s)=>decodeURIComponent(escape(atob(s)))}
function init(){initTheme();initDefaults();bindLogin();bindNav();initStudent();initTeacher();initManuals()}
function initTheme(){document.body.style.fontFamily='Microsoft YaHei'}
try{if(window.Chart&&window.ChartDataLabels){window.Chart.register(window.ChartDataLabels)}}catch(e){}
function initDefaults(){const defQ=[
  {id:'q1',type:'判断',dim:'细胞核的分布及数量',text:'所有真核细胞都有细胞核。',ans:false,exp:'高等植物筛管细胞和哺乳动物成熟红细胞没有细胞核。'},
  {id:'q2',type:'判断',dim:'细胞核的结构',text:'核膜上的核孔允许蛋白质和 RNA 自由进出。',ans:false,exp:'蛋白质需携带信号选择性通过核孔，RNA经核孔进出；DNA不能离开细胞核，小分子不可随意通过。'},
  {id:'q3',type:'判断',dim:'细胞核的结构',text:'染色体和染色质的形状只是不同，但组成完全相同。',ans:true,exp:'二者是同一物质在不同阶段的两种形式，均由DNA和蛋白质组成。'},
  {id:'q4',type:'判断',dim:'细胞核的功能',text:'细胞核是细胞的代谢中心。',ans:false,exp:'细胞核是遗传信息库与调控中心；代谢中心是细胞质基质。'},
  {id:'q5',type:'判断',dim:'细胞核的功能',text:'伞藻嫁接和伞藻核移植的实验结果显示，细胞分裂和分化由细胞核控制。',ans:false,exp:'结论是细胞核控制细胞的形态结构（如伞帽形状），并非直接控制分裂与分化。'},
  {id:'q6',type:'判断',dim:'细胞核的分布及数量',text:'大肠杆菌中的核糖体形成与其核仁相关。',ans:false,exp:'大肠杆菌为原核生物，没有核仁，其核糖体形成不依赖核仁。'},
  {id:'q7',type:'判断',dim:'细胞核的结构',text:'核孔是细胞核与胞质之间物质交换和信息交换的唯一通道。',ans:false,exp:'核孔是主要通道但非唯一，小分子可直接穿过核膜磷脂双层。'},
  {id:'q8',type:'填空',dim:'细胞核的结构',text:'图（1）、（2）、（3）和（4）分别是______、______、______、______。',ans:['染色质','核仁','核膜','核孔'],exp:'（1）染色质、（2）核仁、（3）核膜、（4）核孔'}
];const q=store.get('hx_bank',defQ);state.questions=q;const defRes=[
  {title:'核孔运输动画',dim:'细胞核的结构',url:'https://www.youtube.com/embed/G6phQHBTUms'},
  {title:'染色质与染色体转化3D',dim:'细胞核的结构',url:'https://www.youtube.com/embed/Q6JtqcJ1E3Q'},
  {title:'细胞核功能微课',dim:'细胞核的功能',url:'https://www.youtube.com/embed/4cLxNT7qf6g'},
  {title:'核仁与核糖体形成',dim:'细胞核的结构',url:'https://www.youtube.com/embed/0RBowjzqzMo'}
];state.resources=store.get('hx_res',defRes);state.tasks=store.get('hx_tasks',[]);state.submissions=store.get('hx_subs',[]);state.views=store.get('hx_views',[]);state.stuQuestions=store.get('hx_stu_q',[])}
function bindLogin(){state.role='student';updateLoginFields();const rs=document.getElementById('role-student');const rt=document.getElementById('role-teacher');[rs,rt].forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.role-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.role=b.getAttribute('data-role');updateLoginFields()}));document.getElementById('login-btn').addEventListener('click',()=>{const tip=document.getElementById('login-tip');const name=document.getElementById('login-name').value.trim();const verify=document.getElementById('login-verify').value.trim();if(state.role==='student'&&!name){return showTip(tip)}if(state.role==='teacher'&&!verify){return showTip(tip)}state.user=state.role==='student'?name:'教师';els.loginSection.classList.add('hidden');els.topNav.classList.remove('hidden');const btn=[...document.querySelectorAll('#top-nav .nav-btn')].find(b=>b.getAttribute('data-nav')===state.role);document.querySelectorAll('#top-nav .nav-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(state.role==='student'){els.studentSection.classList.remove('hidden');els.teacherSection.classList.add('hidden')}else{els.teacherSection.classList.remove('hidden');els.studentSection.classList.add('hidden')}document.body.classList.add('logged')})}
function updateLoginFields(){const nameRow=document.getElementById('row-name');const verifyRow=document.getElementById('row-verify');if(state.role==='student'){nameRow.classList.remove('hidden');verifyRow.classList.add('hidden')}else{verifyRow.classList.remove('hidden');nameRow.classList.add('hidden')}}
function showTip(tip){tip.classList.remove('hidden');setTimeout(()=>tip.classList.add('hidden'),2000)}
function bindNav(){document.querySelectorAll('#top-nav .nav-btn').forEach(b=>b.addEventListener('click',()=>{const t=b.getAttribute('data-nav');document.querySelectorAll('#top-nav .nav-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(t==='student'){els.studentSection.classList.remove('hidden');els.teacherSection.classList.add('hidden')}else{els.teacherSection.classList.remove('hidden');els.studentSection.classList.add('hidden')}}));document.getElementById('logout').addEventListener('click',()=>{state.user=null;state.role=null;els.topNav.classList.add('hidden');els.studentSection.classList.add('hidden');els.teacherSection.classList.add('hidden');els.loginSection.classList.remove('hidden')});document.getElementById('logout').addEventListener('click',()=>{document.body.classList.remove('logged')})}
function initStudent(){ui.tabs(document.getElementById('student-section'));ensureCoreVideos();bindStuAssess();bindStuTasks();attachEntryHandlers();bindStuRes()}
function initCozeChat(){
  try{
    if(!window.CozeWebSDK) return;
    const mount=document.getElementById('coze-chat');
    const client=new CozeWebSDK.WebChatClient({
      config:{ bot_id:'7582931962722353162', isIframe:false },
      componentProps:{ title:'核小助' },
      auth:{
        type:'token',
        token:'pat_eA03BNy1hcJtLu68RqjwabJFYPjww8vylMc4hNCSTMbwQuCu15cTmV3KY0W65pyS',
        onRefreshToken:function(){
          return 'pat_eA03BNy1hcJtLu68RqjwabJFYPjww8vylMc4hNCSTMbwQuCu15cTmV3KY0W65pyS'
        }
      },
      ui:{
        base:{ layout:'pc', lang:'zh-CN', icon:'images/核小助.jpg' },
        chatBot:{ title:'核小助', el: mount, uploadable:true, width: 420 },
        asstBtn:{ isNeed:false }
      }
    });
    if(client && typeof client.showChatBot==='function'){
      client.showChatBot();
    }
  }catch(e){}
}
function initTeacher(){ui.tabs(document.getElementById('teacher-section'));bindTeaAI();bindTeaAssess();bindTeaTasks();bindTeaRes()}
function bindStuAI(){const input=document.getElementById('stu-ai-input');const send=document.getElementById('stu-ai-send');const hist=document.getElementById('stu-ai-history');const voice=document.getElementById('stu-voice');const clear=document.getElementById('stu-clear-ai');send.addEventListener('click',()=>{const q=input.value.trim();if(!q)return;appendQA(hist,'Q',q);state.stuQuestions.push({user:state.user,q});store.set('hx_stu_q',state.stuQuestions);const a=aiAnswer(q);appendQA(hist,'A',a);input.value=''});if(voice){voice.addEventListener('click',async()=>{try{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;const r=new SR();r.lang='zh-CN';r.start();r.onresult=(e)=>{const t=e.results[0][0].transcript;input.value=t}}catch{}})}if(clear){clear.addEventListener('click',()=>{hist.innerHTML=''})}}
 
function limit(s,n){if(s.length<=n)return s;return s.slice(0,n-1)+'…'}
function appendQA(hist,t,txt){const row=document.createElement('div');row.className='msg '+(t==='Q'?'user':'ai');const avatar=document.createElement('div');avatar.className='avatar '+(t==='Q'?'user':'ai');avatar.innerText=t==='Q'?'学':'核';const bubble=document.createElement('div');bubble.className='bubble';bubble.innerText=(t==='Q'?limit(txt,50):txt);if(t==='Q'){row.appendChild(bubble);row.appendChild(avatar)}else{row.appendChild(avatar);row.appendChild(bubble)}hist.appendChild(row);hist.scrollTop=hist.scrollHeight}
function aiAnswer(q){const k=q.toLowerCase();if(matchLink(k)){setTimeout(showKnowledgeGraph,0);return '已触发知识图谱绘制：结构—功能—分布的关联'}if(matchMethod(k)){return '你觉得观察细胞核需要先处理细胞吗？\n步骤：1) 固定样品 2) 染色显核 3) 洗涤封片 4) 显微观察 5) 记录分析'}if(matchConcept(k)){return '从结构：核膜、核孔、染色质、核仁\n从功能：遗传信息库与调控中心\n从实例：成熟红细胞与筛管细胞无核，伞藻实验体现核调控'}let a='依据课标要点回答：细胞核是遗传信息库与调控中心，核孔选择运输，染色质在分裂期呈染色体形态';if(k.includes('核孔'))a='核孔选择运输，DNA不外出，蛋白质与RNA凭信号通行';else if(k.includes('染色质'))a='染色质与染色体为同质在不同时期的两种形态';else if(k.includes('核仁'))a='核仁参与核糖体形成，与蛋白质装配相关';else if(k.includes('功能'))a='细胞核负责遗传信息存储与表达调控';else if(k.includes('为什么'))a='由结构与信号选择性决定物质出入与信息传递';return a}
function matchConcept(k){return k.includes('基本概念')||k.includes('概念')||k.includes('是什么')}
function matchMethod(k){return k.includes('实验方法')||k.includes('如何实验')||k.includes('怎么实验')||k.includes('观察')}
function matchLink(k){return k.includes('知识联系')||k.includes('联系')||k.includes('图谱')}
function showKnowledgeGraph(){const hist=document.getElementById('stu-ai-history');if(!hist)return;const wrap=document.createElement('div');wrap.style.border='1px solid #D8BFD8';wrap.style.borderRadius='8px';wrap.style.padding='8px';wrap.style.margin='8px 0';wrap.style.background='#FDF4FF';const title=document.createElement('div');title.innerText='知识联系图谱';title.style.color='#7B1FA2';title.style.fontWeight='700';title.style.marginBottom='6px';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('width','100%');svg.setAttribute('height','220');svg.setAttribute('viewBox','0 0 400 220');function node(x,y,text){const g=document.createElementNS('http://www.w3.org/2000/svg','g');const c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('cx',x);c.setAttribute('cy',y);c.setAttribute('r',18);c.setAttribute('fill','#F3E5F5');c.setAttribute('stroke','#7B1FA2');const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',x);t.setAttribute('y',y+5);t.setAttribute('text-anchor','middle');t.setAttribute('font-size','12');t.setAttribute('fill','#7B1FA2');t.textContent=text;g.appendChild(c);g.appendChild(t);svg.appendChild(g)}
function edge(x1,y1,x2,y2,label){const l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',x1);l.setAttribute('y1',y1);l.setAttribute('x2',x2);l.setAttribute('y2',y2);l.setAttribute('stroke','#BA68C8');l.setAttribute('stroke-width','2');svg.appendChild(l);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',(x1+x2)/2);t.setAttribute('y',(y1+y2)/2-6);t.setAttribute('text-anchor','middle');t.setAttribute('font-size','11');t.setAttribute('fill','#BA68C8');t.textContent=label;svg.appendChild(t)}
node(200,40,'结构');node(80,140,'核膜');node(200,140,'核孔');node(320,140,'染色质');node(200,200,'核仁');edge(200,40,80,140,'界限');edge(200,40,200,140,'通道');edge(200,40,320,140,'载体');edge(200,40,200,200,'装配');node(40,60,'功能');edge(40,60,200,140,'选择运输');edge(40,60,320,140,'遗传表达');node(360,60,'分布/数量');edge(360,60,80,140,'细胞类型');edge(360,60,200,200,'生理状态');wrap.appendChild(title);wrap.appendChild(svg);hist.appendChild(wrap);hist.scrollTop=hist.scrollHeight}
async function callAgent(input){function stripPreface(s){const i=s.indexOf('：');return i>=0?s.slice(i+1):s}try{const res=await fetch('/api/agent/invoke',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agentId:'7582931962722353162',input})});if(!res.ok)throw new Error('授权或网络错误');const data=await res.json();return data.output||data.answer||''}catch(e){const local=aiAnswer(stripPreface(input));return '智能体未连接，临时答复：'+local}}

function bindStuAssess(){document.getElementById('start-diagnose').addEventListener('click',()=>{renderDiagnoseForm()});document.getElementById('to-ai').addEventListener('click',()=>{const wrong=JSON.parse(sessionStorage.getItem('hx_wrong')||'[]');const input=document.getElementById('stu-ai-input');input.value=wrong.length?wrong[0].text:'我哪里理解错了？';document.querySelector('#student-section [data-tab="stu-ai"]').click()});document.getElementById('to-res').addEventListener('click',()=>{const wrong=JSON.parse(sessionStorage.getItem('hx_wrong')||'[]');const dim=wrong.length?wrong[0].dim:'all';document.getElementById('res-filter').value=dim;renderStuRes();document.querySelector('#student-section [data-tab="stu-res"]').click()})}
function qDimTag(d){return d==='细胞核的结构'?'掌握细胞核的结构':d}
function renderDiagnoseForm(){const box=document.getElementById('diagnose-form');box.innerHTML='';
  state.questions.slice(0,7).forEach((q,i)=>{const row=document.createElement('div');row.className='card';const rowLine=document.createElement('div');rowLine.className='row-line';const label=document.createElement('div');label.className='q-text';label.innerText=(i+1)+'. '+q.text;rowLine.appendChild(label);const group=document.createElement('div');group.className='radio-group';['true','false'].forEach(v=>{const b=document.createElement('label');const r=document.createElement('input');r.type='radio';r.name='ans_'+q.id;r.value=v;const s=document.createElement('span');s.innerText=v==='true'?'√':'×';b.appendChild(r);b.appendChild(s);group.appendChild(b)});rowLine.appendChild(group);row.appendChild(rowLine);box.appendChild(row)});
  const fill=state.questions[7];const row=document.createElement('div');row.className='card';const label=document.createElement('div');label.className='q-text';label.innerText='8. '+fill.text;row.appendChild(label);const imgWrap=document.createElement('div');imgWrap.className='image-wrap';const img=document.createElement('img');img.src='images/细胞核结构.png';img.alt='细胞核结构示意图';imgWrap.appendChild(img);row.appendChild(imgWrap);const grid=document.createElement('div');grid.className='fill-four';fill.ans.forEach((_,i)=>{const input=document.createElement('input');input.type='text';input.placeholder='填（'+(i+1)+'）';input.id='ans_q8_'+(i+1);grid.appendChild(input)});row.appendChild(grid);
  box.appendChild(row);
  const submitWrap=document.createElement('div');submitWrap.className='submit-center';const submit=document.createElement('button');submit.className='primary';submit.innerText='提交';submit.addEventListener('click',()=>{setTimeout(gradeDiagnose,500)});submitWrap.appendChild(submit);box.appendChild(submitWrap);
  box.classList.remove('hidden');document.getElementById('diagnose-result').classList.add('hidden')}
function gradeDiagnose(){const res=document.getElementById('diagnose-result');const wrong=[];let score=0;const dims={'细胞核的分布及数量':0,'细胞核的功能':0,'细胞核的结构':0};const dimTotal={'细胞核的分布及数量':0,'细胞核的功能':0,'细胞核的结构':0};const answersRec={};
  state.questions.slice(0,7).forEach(q=>{dimTotal[q.dim]++;const radios=[...document.querySelectorAll('input[name="ans_'+q.id+'"]')];const val=(radios.find(r=>r.checked)?.value==='true');const ok=val===q.ans;answersRec[q.id]={ok,val,dim:q.dim};if(ok){score+=10;dims[q.dim]+=1}else{wrong.push(q)}});
  const fill=state.questions[7];const gold=fill.ans;const got=[];for(let i=1;i<=4;i++){const v=document.getElementById('ans_q8_'+i).value.trim();const dim=mapDim(gold[i-1]);dimTotal[dim]++;const ok=fuzzyEq(v,gold[i-1]);answersRec['q8_'+i]={ok,val:v,dim};if(ok){score+=10;dims[dim]+=1}else{wrong.push({id:'q8_'+i,type:'填空',dim,text:'第'+i+'空：'+fill.text,exp:'标准：'+gold[i-1]})}}
  const percent=score;res.querySelector('.score').innerText='得分 '+percent+' 分';const blind=res.querySelector('.blind');
  const keys=Object.keys(dimTotal).filter(k=>dimTotal[k]>0);const mastery=keys.map(k=>({k,rate:Math.round((dims[k]/dimTotal[k])*100)}));const weak=mastery.filter(x=>x.rate<100).sort((a,b)=>a.rate-b.rate);
  blind.innerText=weak.length?('知识盲区（按薄弱度）：'+weak.map(x=>qDimTag(x.k)+' '+x.rate+'%').join('、')):'暂无盲区';
  const list=document.getElementById('analysis-list');list.innerHTML='';if(wrong.length){wrong.forEach(w=>{const row=document.createElement('div');row.className='item';const err=document.createElement('span');err.className='err';err.innerText=(w.text||w.id)+' · '+qDimTag(w.dim);const arrow=document.createElement('span');arrow.innerText='：';const exp=document.createElement('span');exp.className='exp';if(w.type==='填空'&&typeof w.exp==='string'&&w.exp.startsWith('标准：')){const std=document.createElement('span');std.className='std';std.innerText='标准：';const rest=document.createElement('span');rest.innerText=w.exp.slice(3);exp.appendChild(std);exp.appendChild(rest)}else{exp.innerText=w.exp}row.appendChild(err);row.appendChild(arrow);row.appendChild(exp);list.appendChild(row)})}sessionStorage.setItem('hx_wrong',JSON.stringify(wrong));renderRadar(dims,dimTotal);saveSubmission(percent,wrong,answersRec);res.classList.remove('hidden')}
function validateFill(){const fill=state.questions[7];const gold=fill.ans;let msgs=[];for(let i=1;i<=4;i++){const v=document.getElementById('ans_q8_'+i).value.trim();if(!v){msgs.push('第'+i+'空未填写');continue}if(fuzzyEq(v,gold[i-1])){msgs.push('第'+i+'空正确')}
  else{const sug=suggest(v,gold[i-1]);msgs.push('第'+i+'空错误，提示：'+sug)}}document.getElementById('fill-tip').innerText=msgs.join('；')}
function mapDim(name){return '细胞核的结构'}
function normalize(s){return s.replace(/[\s，。；、]/g,'').toLowerCase()}
function levenshtein(a,b){const m=a.length,n=b.length;const dp=Array.from({length:m+1},()=>Array(n+1).fill(0));for(let i=0;i<=m;i++)dp[i][0]=i;for(let j=0;j<=n;j++)dp[0][j]=j;for(let i=1;i<=m;i++){for(let j=1;j<=n;j++){const cost=a[i-1]===b[j-1]?0:1;dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+cost)}}return dp[m][n]}
function fuzzyEq(a,b){const x=normalize(a),y=normalize(b);if(!x)return false;if(x===y)return true;return levenshtein(x,y)<=1}
function suggest(input,gold){const x=normalize(input),y=normalize(gold);if(levenshtein(x,y)<=2)return '是否想输入：'+gold;return '请核对术语拼写'}
function renderRadar(dims,tot){const keys=Object.keys(dims).filter(k=>tot[k]>0);const ctx=document.getElementById('stu-radar');const dataVals=keys.map(k=>Math.round((dims[k]/tot[k])*100));const cfg={type:'radar',data:{labels:keys,datasets:[{label:'掌握度',data:dataVals,borderColor:'#7B1FA2',backgroundColor:'rgba(248,235,250,0.45)'}]},options:{plugins:{legend:{display:false},datalabels:{color:'#7B1FA2',formatter:(v,context)=>context.chart.data.labels[context.dataIndex]+' '+v,anchor:'end',align:'end',offset:4,font:{weight:'600'}}},scales:{r:{suggestedMin:0,suggestedMax:100,angleLines:{color:'#D8BFD8'},grid:{color:'#E1BEE7'},pointLabels:{color:'#7B1FA2'}}}}};new Chart(ctx,cfg)}
function saveSubmission(score,wrong,answers){const sub={user:state.user,score,wrongDims:[...new Set(wrong.map(w=>w.dim))],answers,time:Date.now()};state.submissions.push(sub);store.set('hx_subs',state.submissions)}
function bindStuTasks(){document.getElementById('refresh-tasks').addEventListener('click',renderStuTasks);const gen=document.getElementById('gen-3d');if(gen){gen.addEventListener('click',start3D)}const add=document.getElementById('add-label');if(add){add.addEventListener('click',addLabel)}renderStuTasks()}
function attachEntryHandlers(){const prep=document.getElementById('btn-prep-video');const algae=document.getElementById('btn-algae-video');const page=document.getElementById('btn-3d-page');if(prep){const box=document.getElementById('content-prep-video');bindToggle(prep,box,()=>renderPrep(box))}if(algae){const box=document.getElementById('content-algae-video');bindToggle(algae,box,()=>renderAlgae(box))}if(page){const box=document.getElementById('content-3d-page');bindToggleModel(page,box,()=>render3DPage(box))}const amoeba=document.getElementById('btn-amoeba-page');if(amoeba){amoeba.addEventListener('click',()=>{window.open('变形虫切割实验.html','_blank')})}const algaeNB=document.getElementById('btn-algae-nbook');if(algaeNB){const box=document.getElementById('content-algae-nbook');bindToggle(algaeNB,box,()=>renderAlgae(box))}const toAI=document.getElementById('btn-to-ai');if(toAI){toAI.addEventListener('click',()=>{document.querySelector('#student-section [data-tab=\"stu-ai\"]').click();const input=document.getElementById('stu-ai-input');input.value='请评价我上传的细胞核模型（结构完整性、准确性），并给出修改建议';input.focus()})}const planeBtn=document.getElementById('btn-plane-structure');if(planeBtn){planeBtn.addEventListener('click',()=>{const st=planeBtn.closest('.subtask');const plane=st?.querySelector('.plane-photo');const model=st?.querySelector('.model-photo');if(!model)return;const show=model.style.display!=='none'&&model.style.display!=='';if(show){model.style.display='none'}else{model.style.display='block';if(plane)plane.style.display='none'}})}}
function bindToggle(btn,box,render){const orig=btn.innerText;btn.addEventListener('click',()=>{const shown=!box.classList.contains('hidden');if(shown){box.classList.add('hidden');btn.innerText=orig}else{btn.innerText='收起内容';box.classList.remove('hidden');if(!box.dataset.loaded){render();box.dataset.loaded='1'}}})}
function bindToggleModel(btn,box,render){const orig=btn.innerText;btn.addEventListener('click',()=>{const shown=!box.classList.contains('hidden');if(shown){box.classList.add('hidden');box.classList.remove('model-expanded');btn.innerText=orig}else{btn.innerText='收起模型界面';box.classList.remove('hidden');box.classList.add('model-expanded');if(!box.dataset.loaded){render();box.dataset.loaded='1'}}})}
function renderPrep(box){box.innerHTML='';const tip=document.createElement('div');tip.innerText='正在加载“细胞核的分布及数量”微课…';const loader=document.createElement('span');loader.className='btn-loader';tip.appendChild(loader);box.appendChild(tip);const v=document.createElement('video');v.controls=true;v.src='video/细胞核的分布及数量.mp4';v.addEventListener('loadeddata',()=>{tip.remove()});box.appendChild(v)}
function renderAlgae(box){box.innerHTML='';const tip=document.createElement('div');tip.innerText='正在加载 NBook 模拟伞藻嫁接及核移植实验…';const loader=document.createElement('span');loader.className='btn-loader';tip.appendChild(loader);box.appendChild(tip);const v=document.createElement('video');v.controls=true;v.src='video/NB演示伞藻嫁接及核移植实验.mp4';v.addEventListener('loadeddata',()=>{tip.remove()});box.appendChild(v)}
function render3DPage(box){box.innerHTML='';const tip=document.createElement('div');tip.innerText='正在加载细胞核三维结构模型…';const loader=document.createElement('span');loader.className='btn-loader';tip.appendChild(loader);box.appendChild(tip);const f=document.createElement('iframe');f.src='细胞核三维结构模型.html';f.addEventListener('load',()=>{tip.remove()});box.appendChild(f)}
function renderAxolotlGuide(box){box.innerHTML='';const wrap=document.createElement('div');const h=document.createElement('div');h.style.color='#7B1FA2';h.style.fontWeight='800';h.style.marginBottom='8px';h.innerText='实验背景与目的';const p1=document.createElement('div');p1.innerText='蝾螈受精卵横缢实验：用细丝将受精卵分成两段，观察两段发育差异，用以分析细胞核对个体发育的调控作用。';const h2=document.createElement('div');h2.style.color='#7B1FA2';h2.style.fontWeight='800';h2.style.margin='10px 0 8px';h2.innerText='关键观察点';const ul=document.createElement('ul');ul.style.margin='0 0 8px 18px';['核所在半部能正常分裂与发育','无核半部发育受限或停止','两半共享的细胞质不决定个体发育方向'].forEach(t=>{const li=document.createElement('li');li.innerText=t;ul.appendChild(li)});const h3=document.createElement('div');h3.style.color='#7B1FA2';h3.style.fontWeight='800';h3.style.margin='10px 0 8px';h3.innerText='结论与讨论';const p3=document.createElement('div');p3.innerText='细胞核作为遗传信息库与表达调控中心，决定胚胎发育方向。该实验与伞藻嫁接、核移植共同支持“细胞核调控形态结构”。';wrap.appendChild(h);wrap.appendChild(p1);wrap.appendChild(h2);wrap.appendChild(ul);wrap.appendChild(h3);wrap.appendChild(p3);box.appendChild(wrap)}
function renderStuTasks(){const list=document.getElementById('stu-task-list');list.innerHTML='';const tasks=state.tasks.filter(t=>t.scope==='全班'||t.scope==='薄弱生');tasks.forEach(t=>{const row=document.createElement('div');row.className='card';row.innerText=t.title+' · '+t.type+' · 截止 '+t.deadline;list.appendChild(row)})}
let three={scene:null,renderer:null,camera:null,mesh:null}
function start3D(){const wrap=document.getElementById('viewer3d');wrap.innerHTML='';const w=wrap.clientWidth||wrap.offsetWidth;const h=wrap.clientHeight||wrap.offsetHeight;three.scene=new THREE.Scene();three.camera=new THREE.PerspectiveCamera(45,w/h,0.1,1000);three.camera.position.z=2.5;three.renderer=new THREE.WebGLRenderer({antialias:true});three.renderer.setSize(w,h);wrap.appendChild(three.renderer.domElement);const geo=new THREE.SphereGeometry(1,32,32);const input=document.getElementById('nucleus-upload');const file=input&&input.files?input.files[0]:null;if(file){const fr=new FileReader();fr.onload=()=>{const tex=new THREE.TextureLoader().load(fr.result);const mat=new THREE.MeshBasicMaterial({map:tex});three.mesh=new THREE.Mesh(geo,mat);three.scene.add(three.mesh);animate3D()};fr.readAsDataURL(file)}else{const mat=new THREE.MeshNormalMaterial();three.mesh=new THREE.Mesh(geo,mat);three.scene.add(three.mesh);animate3D()}}
function animate3D(){function tick(){if(three.mesh){three.mesh.rotation.y+=0.005}three.renderer.render(three.scene,three.camera);requestAnimationFrame(tick)}tick()}
function addLabel(){const wrap=document.getElementById('viewer3d');const text=document.getElementById('label-text').value.trim();if(!text)return;const tag=document.createElement('div');tag.style.position='absolute';tag.style.right='12px';tag.style.top='12px';tag.style.background='#009688';tag.style.color='#fff';tag.style.padding='4px 8px';tag.style.borderRadius='6px';tag.innerText=text;wrap.appendChild(tag)}
function bindStuRes(){document.getElementById('res-filter').addEventListener('change',renderStuRes2);renderStuRes2()}
function sanitizeBiliUrl(u){try{const url=new URL(u);if(url.hostname.includes('bilibili')){if(/\/video\/BV/i.test(url.pathname)){const m=url.pathname.match(/BV[0-9A-Za-z]+/i);const bvid=m?m[0]:null;if(bvid){const embed=new URL('https://player.bilibili.com/player.html');embed.searchParams.set('bvid',bvid);embed.searchParams.set('autoplay','0');return embed.toString()}}if(url.searchParams.has('autoplay')){url.searchParams.set('autoplay','0')}else{url.searchParams.append('autoplay','0')}return url.toString()}}catch(e){}return (u||'').replace(/autoplay=1/ig,'autoplay=0')}
function displayLabel(item){const u=(item.url||'').toLowerCase();const t=(item.title||'').toLowerCase();const rawTitle=item.title||'';const d=item.dim||'';if(u.includes('bilibili')){if(t.includes('结构和功能'))return rawTitle;if(t.includes('染色质')||t.includes('染色体'))return '染色体与染色质';if(t.includes('核孔'))return '核孔';if(t.includes('之歌'))return rawTitle;return rawTitle}if(u.endsWith('.mp4')){if(t.includes('分布及数量'))return '细胞核的分布及数量';if(t.includes('nbook')||t.includes('nb演示')||t.includes('nb')||t.includes('伞藻')||t.includes('核移植'))return '细胞核的功能';return rawTitle}return rawTitle+' · '+d}
function renderStuRes2(){const box=document.getElementById('stu-res-list');box.innerHTML='';const dim=document.getElementById('res-filter').value;const push=store.get('hx_push',null);if(push&&(dim==='all'||push.dim===dim)){const p=document.createElement('div');p.className='card resource-card';const h=document.createElement('div');h.className='title';h.innerText='教师推送 · '+displayLabel(push);const wrap=document.createElement('div');wrap.className='video-wrap';const tip=document.createElement('div');tip.className='video-tip';tip.innerText='资源加载中…';wrap.appendChild(tip);if((push.url||'').toLowerCase().endsWith('.mp4')){const v=document.createElement('video');v.controls=true;v.src=push.url;v.addEventListener('loadeddata',()=>{trackView(push);tip.remove()});v.addEventListener('error',()=>{tip.innerText='视频未找到或无法加载'});wrap.appendChild(v)}else{const iframe=document.createElement('iframe');iframe.src=sanitizeBiliUrl(push.url);iframe.loading='lazy';let done=false;iframe.addEventListener('load',()=>{done=true;trackView(push);tip.remove()});iframe.addEventListener('error',()=>{tip.innerText='外部资源无法访问'});setTimeout(()=>{if(!done){tip.innerText='外部资源连接超时'}} ,10000);wrap.appendChild(iframe)}p.appendChild(h);p.appendChild(wrap);box.appendChild(p)}const items=state.resources.filter(r=>dim==='all'||r.dim===dim);items.forEach(r=>{const card=document.createElement('div');card.className='card resource-card';const title=document.createElement('div');title.className='title';title.innerText=displayLabel(r);const wrap=document.createElement('div');wrap.className='video-wrap';const tip=document.createElement('div');tip.className='video-tip';tip.innerText='资源加载中…';wrap.appendChild(tip);if((r.url||'').toLowerCase().endsWith('.mp4')){const v=document.createElement('video');v.controls=true;v.src=r.url;v.addEventListener('loadeddata',()=>{trackView(r);tip.remove()});v.addEventListener('error',()=>{tip.innerText='视频未找到或无法加载'});wrap.appendChild(v)}else{const iframe=document.createElement('iframe');iframe.src=sanitizeBiliUrl(r.url);iframe.loading='lazy';let done=false;iframe.addEventListener('load',()=>{done=true;trackView(r);tip.remove()});iframe.addEventListener('error',()=>{tip.innerText='外部资源无法访问'});setTimeout(()=>{if(!done){tip.innerText='外部资源连接超时'}} ,10000);wrap.appendChild(iframe)}card.appendChild(title);card.appendChild(wrap);box.appendChild(card)})}
function renderStuRes(){const box=document.getElementById('stu-res-list');box.innerHTML='';const dim=document.getElementById('res-filter').value;const push=store.get('hx_push',null);if(push&&(dim==='all'||push.dim===dim)){const p=document.createElement('div');p.className='card resource-card';const h=document.createElement('div');h.className='title';h.innerText='教师推送 · '+push.title+' · '+push.dim;const wrap=document.createElement('div');wrap.className='video-wrap';const tip=document.createElement('div');tip.className='video-tip';tip.innerText='资源加载中…';wrap.appendChild(tip);if((push.url||'').toLowerCase().endsWith('.mp4')){const v=document.createElement('video');v.controls=true;v.src=push.url;v.addEventListener('loadeddata',()=>{trackView(push);tip.remove()});v.addEventListener('error',()=>{tip.innerText='视频未找到或无法加载'});wrap.appendChild(v)}else{const iframe=document.createElement('iframe');iframe.src=push.url;iframe.loading='lazy';let done=false;iframe.addEventListener('load',()=>{done=true;trackView(push);tip.remove()});iframe.addEventListener('error',()=>{tip.innerText='外部资源无法访问'});setTimeout(()=>{if(!done){tip.innerText='外部资源连接超时'}} ,10000);wrap.appendChild(iframe)}p.appendChild(h);p.appendChild(wrap);box.appendChild(p)}const items=state.resources.filter(r=>dim==='all'||r.dim===dim);items.forEach(r=>{const card=document.createElement('div');card.className='card resource-card';const title=document.createElement('div');title.className='title';title.innerText=r.title+' · '+r.dim;const wrap=document.createElement('div');wrap.className='video-wrap';const tip=document.createElement('div');tip.className='video-tip';tip.innerText='资源加载中…';wrap.appendChild(tip);if((r.url||'').toLowerCase().endsWith('.mp4')){const v=document.createElement('video');v.controls=true;v.src=r.url;v.addEventListener('loadeddata',()=>{trackView(r);tip.remove()});v.addEventListener('error',()=>{tip.innerText='视频未找到或无法加载'});wrap.appendChild(v)}else{const iframe=document.createElement('iframe');iframe.src=r.url;iframe.loading='lazy';let done=false;iframe.addEventListener('load',()=>{done=true;trackView(r);tip.remove()});iframe.addEventListener('error',()=>{tip.innerText='外部资源无法访问'});setTimeout(()=>{if(!done){tip.innerText='外部资源连接超时'}} ,10000);wrap.appendChild(iframe)}card.appendChild(title);card.appendChild(wrap);box.appendChild(card)})}
function trackView(r){state.views.push({user:state.user,title:r.title,dim:r.dim,time:Date.now()});store.set('hx_views',state.views)}
function bindTeaAI(){document.getElementById('prep-gen').addEventListener('click',()=>{const t=document.getElementById('prep-input').value.trim();const out=document.getElementById('prep-out');const goals=['理解核孔选择运输','掌握染色质到染色体转化','明确核仁与核糖体关系'];const diff=['识别信号序列机制','区分DNA与RNA出入核','联系分裂期结构变化'];const flow=['导入：核功能视频','讲解：结构与功能','探究：伞藻实验','巩固：诊断题','拓展：克隆猴讨论'];out.innerText='教学目标\n- '+goals.join('\n- ')+'\n重难点\n- '+diff.join('\n- ')+'\n教学流程\n- '+flow.join('\n- ')});document.getElementById('exam-gen').addEventListener('click',()=>{const out=document.getElementById('exam-out');const base=['判断：核孔是否允许DNA通过','选择：染色质在分裂期的变化'];const mid=['分析：伞藻实验现象与结论','填空：核孔运输依赖____'];const adv=['探究：设计验证核定位信号实验','论述：核功能失常的影响'];out.innerText='基础\n- '+base.join('\n- ')+'\n进阶\n- '+mid.join('\n- ')+'\n拓展\n- '+adv.join('\n- ')});const faq=document.getElementById('faq-out');const qs=state.stuQuestions.slice(-10).map(x=>'· '+x.q).join('\n');faq.innerText=qs||'暂无数据'}
function bindTeaAssess(){renderClassStats();renderHeatmap();renderTeaCharts();renderTeachingSuggestions();document.getElementById('export-report').addEventListener('click',exportReport);renderBankUI();document.getElementById('bank-add').addEventListener('click',addBankItem);document.getElementById('bank-save').addEventListener('click',saveBank);const sort=document.getElementById('sort-metric');if(sort){sort.addEventListener('change',()=>{renderTeaCharts();renderTeachingSuggestions()})}}
function renderClassStats(){const stats=document.getElementById('class-stats');if(!state.submissions.length){stats.innerText='暂无答题数据';return}const avg=Math.round(state.submissions.reduce((a,b)=>a+b.score,0)/state.submissions.length);const allWrong=state.submissions.flatMap(s=>s.wrongDims);const top=Object.entries(countBy(allWrong)).sort((a,b)=>b[1]-a[1]).slice(0,3).map(x=>qDimTag(x[0])).join('、');const perQ=perQuestionStats();stats.innerText='班级平均分 '+avg+' 分\n易错点TOP3：'+top+'\n每题正确率：'+Object.entries(perQ.acc).map(([k,v])=>k+': '+Math.round(v*100)+'%').join('，')}
function perQuestionStats(){const ids=['q1','q2','q3','q4','q5','q6','q7','q8_1','q8_2','q8_3','q8_4'];const acc={};const err={};ids.forEach(id=>{let ok=0,tot=0;state.submissions.forEach(s=>{if(s.answers&&id in s.answers){tot++;if(s.answers[id].ok)ok++}});acc[id]=tot?ok/tot:0;err[id]=tot?(tot-ok):0});return {acc,err}}
function renderTeaCharts(){const boxBar=document.getElementById('tea-bar');const boxPie=document.getElementById('tea-pie');if(!boxBar||!boxPie)return;const {acc,err}=perQuestionStats();const sort=document.getElementById('sort-metric')?.value||'acc';const labels=Object.keys(acc).sort((a,b)=>sort==='acc'?acc[b]-acc[a]:err[b]-err[a]);const accData=labels.map(k=>Math.round(acc[k]*100));const errData=labels.map(k=>err[k]);new Chart(boxBar,{type:'bar',data:{labels,datasets:[{label:'正确率(%)',data:accData,backgroundColor:'rgba(0,150,136,0.4)',borderColor:'#009688'}]},options:{plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,max:100}}}});const dimsCount=countBy(state.submissions.flatMap(s=>s.wrongDims));new Chart(boxPie,{type:'pie',data:{labels:Object.keys(dimsCount),datasets:[{data:Object.values(dimsCount),backgroundColor:['#26A69A','#80CBC4','#4DB6AC','#B2DFDB']}]} ,options:{plugins:{legend:{position:'bottom'}}}})}
function renderTeachingSuggestions(){const box=document.getElementById('suggest-out');if(!box)return;const wrong=state.submissions.flatMap(s=>s.wrongDims);const ranked=Object.entries(countBy(wrong)).sort((a,b)=>b[1]-a[1]);const topDims=ranked.slice(0,3).map(x=>x[0]);const lines=[
  '针对薄弱知识点补充专项练习：'+(topDims.join('、')||'暂无数据'),
  '结合图表数据强化概念理解：按正确率排序讲评',
  '布置纠错任务：错题解析+资源观看统计',
  '分层教学：为掌握度低的维度安排支架活动'
];box.innerText=lines.map(l=>'· '+l).join('\n')}
function renderHeatmap(){const box=document.getElementById('tea-heatmap');box.innerHTML='';const dims=['细胞核的分布及数量','细胞核的功能','细胞核的结构'];const data=countBy(state.submissions.flatMap(s=>s.wrongDims));dims.forEach(d=>{const cell=document.createElement('div');cell.className='heatcell';const wrong=data[d]||0;const total=state.submissions.length||1;const ratio=1-wrong/total;const c=Math.round(255*ratio);cell.style.background='rgb('+Math.round(255-c)+','+c+','+c+')';cell.innerText=qDimTag(d)+' 掌握度 '+Math.round(ratio*100)+'%';box.appendChild(cell)})}
function exportReport(){const {Document,Packer,Paragraph,TextRun}=window.docx;const statsTxt=getText(document.getElementById('class-stats'))||'';const suggestTxt=getText(document.getElementById('suggest-out'))||'暂无教学建议';const children=[new Paragraph({children:[new TextRun('学情报告')],heading:"Heading1"}),new Paragraph('班级答题概览'),new Paragraph(statsTxt),new Paragraph({children:[new TextRun('教学建议')],heading:"Heading2"})];suggestTxt.split('\n').forEach(l=>children.push(new Paragraph(l)));const doc=new Document({sections:[{children}]});Packer.toBlob(doc).then(b=>{saveBlob(b,'学情报告.docx')})}
function getText(el){return el.innerText||el.textContent||''}
function saveBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function renderBankUI(){const list=document.getElementById('bank-list');list.innerHTML='';state.questions.forEach((q,i)=>{const row=document.createElement('div');row.className='card';row.innerText=(i+1)+'. '+q.type+' · '+qDimTag(q.dim)+' · '+q.text+' · 答案:'+q.ans+' · 解析:'+q.exp;list.appendChild(row)})}
function addBankItem(){const text=document.getElementById('bank-q').value.trim();const type=document.getElementById('bank-type').value;const dim=document.getElementById('bank-dim').value;const ans=document.getElementById('bank-ans').value.trim();const exp=document.getElementById('bank-exp').value.trim();if(!text||!ans)return;const id='q'+Math.random().toString(36).slice(2,7);const item={id,type,dim,text,ans:type==='判断'?ans==='true':ans,exp};state.questions.push(item);renderBankUI()}
function saveBank(){store.set('hx_bank',state.questions)}
function bindTeaTasks(){document.getElementById('task-create').addEventListener('click',()=>{const title=document.getElementById('task-title').value.trim();const type=document.getElementById('task-type').value;const deadline=document.getElementById('task-deadline').value;const desc=document.getElementById('task-desc').value.trim();if(!title)return;const t={id:'t'+Math.random().toString(36).slice(2,7),title,type,deadline,desc,scope:'全班',created:Date.now()};state.tasks.push(t);store.set('hx_tasks',state.tasks);renderTeaTasks()});document.getElementById('task-push').addEventListener('click',()=>{const scope=document.getElementById('push-scope').value;state.tasks=state.tasks.map(t=>({...t,scope}));store.set('hx_tasks',state.tasks);renderTeaTasks()});renderTeaTasks()}
function renderTeaTasks(){const list=document.getElementById('tea-task-list');list.innerHTML='';state.tasks.forEach(t=>{const row=document.createElement('div');row.className='card';const title=document.createElement('div');title.innerText=t.title+' · '+t.type+' · 截止 '+t.deadline+' · 推送 '+t.scope;const btn=document.createElement('button');btn.className='secondary';btn.innerText='生成完成质量报告';btn.addEventListener('click',()=>{const subs=state.submissions.filter(s=>true);const txt='提交数 '+subs.length+'\n平均分 '+(subs.length?Math.round(subs.reduce((a,b)=>a+b.score,0)/subs.length):0);const b=new Blob([txt],{type:'text/plain'});saveBlob(b,'任务质量报告.txt')});row.appendChild(title);row.appendChild(btn);list.appendChild(row)})}
function bindTeaRes(){document.getElementById('res-add').addEventListener('click',()=>{const title=document.getElementById('res-title').value.trim();const url=document.getElementById('res-url').value.trim();const dim=document.getElementById('res-dim').value;if(!title||!url)return;state.resources.push({title,url,dim});store.set('hx_res',state.resources);renderTeaRes()});document.getElementById('res-smart-push').addEventListener('click',smartPush);renderTeaRes();renderResStats()}
function renderTeaRes(){const list=document.getElementById('tea-res-list');list.innerHTML='';state.resources.forEach(r=>{const row=document.createElement('div');row.className='card';row.innerText=r.title+' · '+r.dim+' · '+r.url;list.appendChild(row)})}
function smartPush(){const wrong=state.submissions.flatMap(s=>s.wrongDims);if(!wrong.length)return;const worst=Object.entries(countBy(wrong)).sort((a,b)=>b[1]-a[1])[0][0];const cand=state.resources.find(r=>r.dim===worst);if(cand){store.set('hx_push',cand)}renderResStats()}
function renderResStats(){const box=document.getElementById('res-stats');const counts=countBy(state.views.map(v=>v.dim));box.innerText=Object.keys(counts).length?Object.entries(counts).map(([k,v])=>k+'：'+v+'次').join('\n'):'暂无统计'}
function countBy(arr){return arr.reduce((m,x)=>{m[x]=(m[x]||0)+1;return m},{})}
function ensureCoreVideos(){const need=[{title:'“细胞核的分布及数量”微课',dim:'细胞核的分布及数量',url:'video/细胞核的分布及数量.mp4'},{title:'NBook模拟伞藻嫁接及核移植实验',dim:'细胞核的功能',url:'video/NB演示伞藻嫁接及核移植实验.mp4'},{title:'细胞核的结构和功能之歌（完整版）',dim:'细胞核的结构',url:'https://www.bilibili.com/video/BV1me411976H/?spm_id_from=333.337.search-card.all.click&vd_source=998fb6ed1626ba27a2be0aadd4b759e8'},{title:'染色质与染色体',dim:'细胞核的结构',url:'https://www.bilibili.com/video/BV1HE41157Ux/?spm_id_from=333.337.search-card.all.click&vd_source=998fb6ed1626ba27a2be0aadd4b759e8'},{title:'核孔的结构（动画演示）',dim:'细胞核的结构',url:'https://www.bilibili.com/video/BV1He411w7jB/?spm_id_from=333.337.search-card.all.click&vd_source=998fb6ed1626ba27a2be0aadd4b759e8'}];let added=false;need.forEach(n=>{if(!state.resources.some(r=>r.url===n.url)){state.resources.push(n);added=true}});if(added)store.set('hx_res',state.resources)}
function initManuals(){const stuBtn=document.getElementById('open-stu-manual');if(stuBtn)stuBtn.addEventListener('click',()=>openModal('modal-stu'));const teaBtn=document.getElementById('open-tea-manual');if(teaBtn)teaBtn.addEventListener('click',()=>openModal('modal-tea'));document.querySelectorAll('.modal .close').forEach(b=>b.addEventListener('click',()=>closeModal(b.getAttribute('data-close'))));const stuBody=document.getElementById('manual-stu-body');const teaBody=document.getElementById('manual-tea-body');if(stuBody)stuBody.innerText='学生端操作手册\n1) 进入学情评测中心，点击开始诊断\n2) 完成7道判断题（√/×）与4个填空\n3) 点击提交，查看得分、知识盲区与雷达图\n4) 通过按钮跳转核小助答疑或学习资源补救\n平板横屏会自动放大输入框，便于触控';if(teaBody)teaBody.innerText='教师端操作手册\n1) 打开学情评测中心查看班级概览\n2) 通过热力图与柱状/饼图识别薄弱知识点\n3) 一键导出Word学情报告\n4) 在题库管理中维护诊断题版本并保存';const feat=document.getElementById('feature-body');if(feat)feat.innerText='模块功能清单与AI赋能亮点\n学生端：学、练、问、查\n教师端：评、管、推、析\nAI赋能：自动批改与错题解析、联动资源推送、可视化学情图表'}
function openModal(id){document.getElementById(id).style.display='block'}
function closeModal(id){document.getElementById(id).style.display='none'}
window.addEventListener('load',()=>{init();initCozeChat()})
